name: sist_prestamo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0-97.0.dev

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.27.0
  provider: ^6.1.4
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.32
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  sqlite3: ^2.7.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.27.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
