import 'package:flutter/foundation.dart';

import 'package:sist_prestamo/controllers/usuario_factory.dart';
import 'package:sist_prestamo/controllers/database_config.dart';

import 'package:sist_prestamo/models/persona_model.dart';
import 'package:sist_prestamo/models/cliente_model.dart';

class ClienteService {
  // ==============================
  // PATRON SINGLETON
  // ClienteService utiliza Singleton
  // para garantizar una unica instancia
  // durante toda la ejecucion del sistema.
  // Defensa: Patron Creacional.
  // Razon en Cuentas Claras: centraliza
  // el acceso a cliente/persona/usuario.
  // ==============================
  static final ClienteService _instance = ClienteService._internal();

  factory ClienteService() {
    return _instance;
  }

  ClienteService._internal();

  final localDb = DatabaseConfig.client;

  // =========================
  // INSERTAR CLIENTE
  // =========================

  Future<void> insertarCliente(ClienteModel cliente) async {
    try {
      await localDb.from('cliente').insert(cliente.toJson());

      debugPrint('CLIENTE INSERTADO');
    } catch (e) {
      debugPrint('ERROR INSERTAR CLIENTE: $e');

      rethrow;
    }
  }

  Future<void> insertarClienteConPersona(
    PersonaModel persona,
    ClienteModel cliente, {
    String tipoUsuario = 'CLIENTE',
    required String username,
    required String password,
  }) async {
    try {
      _validarPersonaCliente(persona, cliente);
      final credenciales = await _resolverCredenciales(
        persona: persona,
        username: username,
        password: password,
      );
      final rol = await _rolPorNombre(tipoUsuario);
      await _guardarPersona(persona);
      final authUser = await _crearUsuarioAuth(
        username: credenciales.username,
        password: credenciales.password,
        autoGenerated: credenciales.autoGenerated,
      );

      if (tipoUsuario.toUpperCase() == 'COBRADOR') {
        await _guardarCobrador(persona.ciPersona);
      } else {
        final clienteExistente = await localDb
            .from('cliente')
            .select('id_cliente')
            .eq('ci_persona', cliente.ciPersona)
            .maybeSingle();

        if (clienteExistente != null) {
          throw Exception('Ya existe un cliente registrado con ese CI');
        }

        await localDb.from('cliente').insert(cliente.toJson());
      }

      await _guardarUsuarioPersona(
        persona: persona,
        tipoUsuario: tipoUsuario,
        rol: rol,
        authUserId: authUser.idUsuario,
        username: authUser.username,
      );
      debugPrint('CLIENTE Y PERSONA INSERTADOS');
    } catch (e) {
      debugPrint('ERROR INSERTAR CLIENTE CON PERSONA: $e');

      rethrow;
    }
  }

  Future<void> actualizarClienteConPersona(
    PersonaModel persona,
    ClienteModel cliente,
  ) async {
    try {
      _validarPersonaCliente(persona, cliente);
      await _guardarPersona(persona);

      await localDb
          .from('cliente')
          .update(cliente.toJson())
          .eq('id_cliente', cliente.idCliente);

      debugPrint('CLIENTE Y PERSONA ACTUALIZADOS');
    } catch (e) {
      debugPrint('ERROR ACTUALIZAR CLIENTE CON PERSONA: $e');

      rethrow;
    }
  }

  Future<void> _guardarPersona(PersonaModel persona) async {
    final personaExistente = await localDb
        .from('persona')
        .select('ci_persona')
        .eq('ci_persona', persona.ciPersona)
        .maybeSingle();

    if (personaExistente == null) {
      await _insertarPersonaSeguro(persona);
      return;
    }

    await _actualizarPersonaSeguro(persona);
  }

  // =========================
  // LISTAR CLIENTES
  // =========================

  Future<List<Map<String, dynamic>>> listarClientes() async {
    try {
      final clientes = await localDb.from('cliente').select();
      final personas = await _listarSeguro('persona');
      final personasByCi = {
        for (final persona in personas)
          if (persona['ci'] != null) persona['ci'].toString(): persona,
        for (final persona in personas)
          if (persona['ci_persona'] != null)
            persona['ci_persona'].toString(): persona,
      };

      return List<Map<String, dynamic>>.from(clientes).map((cliente) {
        return {
          ...cliente,
          'persona': personasByCi[cliente['ci_persona']?.toString() ?? ''],
        };
      }).toList();
    } catch (e) {
      debugPrint('ERROR LISTAR CLIENTES: $e');

      return [];
    }
  }

  // =========================
  // ACTUALIZAR CLIENTE
  // =========================

  Future<void> actualizarCliente(ClienteModel cliente) async {
    try {
      await localDb
          .from('cliente')
          .update(cliente.toJson())
          .eq('id_cliente', cliente.idCliente);

      debugPrint('CLIENTE ACTUALIZADO');
    } catch (e) {
      debugPrint('ERROR ACTUALIZAR CLIENTE: $e');

      rethrow;
    }
  }

  Future<void> _insertarPersonaSeguro(PersonaModel persona) async {
    try {
      await localDb.from('persona').insert(persona.toJson());
    } catch (_) {
      final payload = persona.toJson()
        ..remove('latitud')
        ..remove('longitud');
      await localDb.from('persona').insert(payload);
    }
  }

  Future<void> _actualizarPersonaSeguro(PersonaModel persona) async {
    try {
      await localDb
          .from('persona')
          .update(persona.toJson())
          .eq('ci_persona', persona.ciPersona);
    } catch (_) {
      final payload = persona.toJson()
        ..remove('latitud')
        ..remove('longitud');
      await localDb
          .from('persona')
          .update(payload)
          .eq('ci_persona', persona.ciPersona);
    }
  }

  Future<List<Map<String, dynamic>>> _listarSeguro(String table) async {
    try {
      final response = await localDb.from(table).select();
      return List<Map<String, dynamic>>.from(response);
    } catch (e, stackTrace) {
      if (table == 'rol') {
        debugPrint('ERROR REAL DE BASE LOCAL: $e');
        debugPrint('STACKTRACE ROLES: $stackTrace');
        rethrow;
      }
      return [];
    }
  }

  // =========================
  // ELIMINAR CLIENTE
  // =========================

  Future<void> eliminarCliente(int idCliente) async {
    try {
      await localDb
          .from('cliente')
          .update({'estado': false})
          .eq('id_cliente', idCliente);

      debugPrint('CLIENTE DESACTIVADO');
    } catch (e) {
      debugPrint('ERROR ELIMINAR CLIENTE: $e');

      rethrow;
    }
  }

  Future<void> _guardarCobrador(String ciPersona) async {
    final existente = await localDb
        .from('cobrador')
        .select('id_cobrador')
        .eq('ci_persona', ciPersona)
        .maybeSingle();
    if (existente != null) return;
    await localDb.from('cobrador').insert({'ci_persona': ciPersona});
  }

  Future<void> _guardarUsuarioPersona({
    required PersonaModel persona,
    required String tipoUsuario,
    required Map<String, dynamic> rol,
    required String authUserId,
    required String username,
  }) async {
    final existentePorCi = await localDb
        .from('usuario')
        .select('id_usuario')
        .eq('ci_persona', persona.ciPersona)
        .maybeSingle();
    final existentePorId = await localDb
        .from('usuario')
        .select('id_usuario')
        .eq('id_usuario', authUserId)
        .maybeSingle();
    final existentePorUsername = await localDb
        .from('usuario')
        .select('id_usuario')
        .eq('username', username)
        .maybeSingle();
    final existente = existentePorCi ?? existentePorId ?? existentePorUsername;

    final esCobrador = tipoUsuario.trim().toUpperCase() == 'COBRADOR';
    final data = esCobrador
        ? UsuarioFactory.crearCobrador(
            ciPersona: persona.ciPersona,
            idRol: rol['id_rol'],
            username: username,
          )
        : UsuarioFactory.crearCliente(
            ciPersona: persona.ciPersona,
            idRol: rol['id_rol'],
            username: username,
          );

    if (existente == null) {
      debugPrint('Insert usuario local');
      await localDb.from('usuario').insert({'id_usuario': authUserId, ...data});
      return;
    }

    await localDb
        .from('usuario')
        .update(data)
        .eq('id_usuario', existente['id_usuario']);
  }

  void _validarPersonaCliente(PersonaModel persona, ClienteModel cliente) {
    if (persona.ciPersona.trim().isEmpty) {
      throw Exception('El CI de la persona es obligatorio.');
    }
    if (cliente.ciPersona.trim().isEmpty) {
      throw Exception('El CI del cliente es obligatorio.');
    }
    if (persona.ciPersona.trim() != cliente.ciPersona.trim()) {
      throw Exception(
        'El CI de persona (${persona.ciPersona}) no coincide con el CI del cliente (${cliente.ciPersona}).',
      );
    }
    if (persona.nombres.trim().isEmpty) {
      throw Exception('El nombre de la persona es obligatorio.');
    }
    if (persona.apellidoPaterno.trim().isEmpty) {
      throw Exception('El apellido paterno de la persona es obligatorio.');
    }
  }

  Future<Map<String, dynamic>> _rolPorNombre(String nombre) async {
    final roles = await _listarRoles();
    final buscado = nombre.trim().toUpperCase();
    debugPrint('ROL BUSCADO: $buscado');
    debugPrint(
      'ROLES DISPONIBLES: '
      '${roles.map((item) => item['nombre']?.toString()).toList()}',
    );
    final rol = roles.cast<Map<String, dynamic>?>().firstWhere(
      (item) => item?['nombre']?.toString().trim().toUpperCase() == buscado,
      orElse: () => null,
    );
    debugPrint('ROL ENCONTRADO: $rol');
    if (rol == null) {
      final disponibles = roles
          .map((item) => item['nombre']?.toString())
          .whereType<String>()
          .join(', ');
      throw Exception(
        'No existe el rol $nombre en la tabla rol. Roles disponibles: $disponibles',
      );
    }
    debugPrint('Rol encontrado: ${rol['nombre']}');
    debugPrint('ID Rol: ${rol['id_rol']}');
    return rol;
  }

  Future<List<Map<String, dynamic>>> _listarRoles() async {
    try {
      debugPrint('CONSULTANDO TABLA ROL');
      final response = await localDb.from('rol').select();
      debugPrint('RESPUESTA ROL: $response');
      debugPrint('TIPO RESPUESTA: ${response.runtimeType}');
      debugPrint('TOTAL REGISTROS: ${response.length}');

      final roles = List<Map<String, dynamic>>.from(response);
      debugPrint('ROLES RECUPERADOS: $roles');
      debugPrint('TOTAL ROLES: ${roles.length}');
      if (roles.isEmpty) debugPrint('ROL VACIO DESDE BASE LOCAL');
      return roles;
    } catch (e, stackTrace) {
      debugPrint('ERROR REAL DE BASE LOCAL: $e');
      debugPrint('STACKTRACE ROLES: $stackTrace');
      rethrow;
    }
  }

  Future<_AuthUsuario> _crearUsuarioAuth({
    required String username,
    required String password,
    required bool autoGenerated,
  }) async {
    var email = username.trim();
    final previousSession = localDb.auth.currentSession;
    var attempt = 0;

    while (true) {
      final usuarioLocal = await localDb
          .from('usuario')
          .select('id_usuario')
          .eq('username', email)
          .maybeSingle();
      if (usuarioLocal?['id_usuario'] != null) {
        if (!autoGenerated) {
          debugPrint('Usuario ya existente');
          return _AuthUsuario(
            idUsuario: usuarioLocal!['id_usuario'].toString(),
            username: email,
          );
        }
        attempt++;
        email = _emailConSufijo(username, attempt);
        continue;
      }

      try {
        final response = await localDb.auth.signUp(
          email: email,
          password: password,
        );
        final userId = response.user.id;
        debugPrint('Usuario Auth creado');

        if (previousSession?.refreshToken != null &&
            localDb.auth.currentUser?.id != previousSession!.user.id) {
          await localDb.auth.setSession(previousSession.refreshToken!);
        }

        if (autoGenerated) {
          debugPrint('Usuario generado automáticamente: $email');
        }
        return _AuthUsuario(idUsuario: userId, username: email);
      } catch (e) {
        if (previousSession?.refreshToken != null &&
            localDb.auth.currentUser?.id != previousSession!.user.id) {
          await localDb.auth.setSession(previousSession.refreshToken!);
        }
        final text = e.toString().toLowerCase();
        if (text.contains('user_already_exists') ||
            text.contains('already registered') ||
            text.contains('already exists')) {
          debugPrint('Usuario ya existente');
          if (autoGenerated) {
            attempt++;
            email = _emailConSufijo(username, attempt);
            continue;
          }
          final local = await localDb
              .from('usuario')
              .select('id_usuario')
              .eq('username', email)
              .maybeSingle();
          if (local?['id_usuario'] != null) {
            return _AuthUsuario(
              idUsuario: local!['id_usuario'].toString(),
              username: email,
            );
          }
          throw Exception(
            'El correo ya existe en Base local Auth, pero no tiene registro local en usuario. Revise la tabla usuario.',
          );
        }
        throw Exception('No se pudo crear el acceso de usuario $email.');
      }
    }
  }

  Future<_CredencialesUsuario> _resolverCredenciales({
    required PersonaModel persona,
    required String username,
    required String password,
  }) async {
    final email = username.trim();
    if (email.isNotEmpty) {
      return _CredencialesUsuario(
        username: email,
        password: password.trim().isEmpty ? '123456' : password.trim(),
        autoGenerated: false,
      );
    }

    final base = _slug('${persona.nombres}${persona.apellidoPaterno}');
    final generated =
        '${base.isEmpty ? persona.ciPersona : base}@cuentasclaras.com';
    debugPrint('Usuario generado automáticamente');
    return _CredencialesUsuario(
      username: generated,
      password: '123456',
      autoGenerated: true,
    );
  }

  String _emailConSufijo(String email, int suffix) {
    final parts = email.split('@');
    if (parts.length != 2) return email;
    return '${parts[0]}$suffix@${parts[1]}';
  }

  String _slug(String value) {
    return value.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '').trim();
  }
}

class _CredencialesUsuario {
  final String username;
  final String password;
  final bool autoGenerated;

  const _CredencialesUsuario({
    required this.username,
    required this.password,
    required this.autoGenerated,
  });
}

class _AuthUsuario {
  final String idUsuario;
  final String username;

  const _AuthUsuario({required this.idUsuario, required this.username});
}
